name: Deploy Game to Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Download Raylib
        run: |
          wget https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_webassembly.zip
          unzip raylib-5.0_webassembly.zip

      - name: Compile Game
        run: |
          mkdir public
          em++ gui_chess.cpp -o public/index.html -Os -Wall raylib-5.0_webassembly/lib/libraylib.a -I raylib-5.0_webassembly/include -I include -s USE_GLFW=3 -s ASYNCIFY -DPLATFORM_WEB --preload-file assets

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
